language: rust
# Cache settings based on https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry

git:
  depth: 1
  quiet: true

os:
  - linux
  - osx

rust:
  - nightly
  - beta
  - stable

addons:
  apt:
    packages:
    - libssl-dev

script:
  - cargo build --features all && cargo test --features all && cargo doc --features all
  - cargo build --no-default-features --features read
  - cargo build --no-default-features --features write
  - cargo build --no-default-features --features read_core,write_core,coff
  - cargo build --no-default-features --features read_core,write_core,elf
  - cargo build --no-default-features --features read_core,write_core,macho
  - cargo build --no-default-features --features read_core,pe
  - cargo build --no-default-features --features read_core,wasm
  - if [ "$TRAVIS_OS_NAME" = linux ] && [ "$TRAVIS_RUST_VERSION" = stable ]; then
      rustup component add rustfmt;
      cargo fmt -- --check;
    fi

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo install -f cargo-tarpaulin;
      cargo tarpaulin --features all --ciserver travis-ci --coveralls $TRAVIS_JOB_ID;
    fi
