language: rust
cache: cargo

git:
  depth: 1
  quiet: true

os:
  - linux
  - osx

rust:
  - nightly
  - beta
  - stable

addons:
  apt:
    packages:
    - libssl-dev

before_install:
  - rustup component add rustfmt
  - cargo fmt -- --check

before_cache:
  - if [ "$TRAVIS_OS_NAME" = linux ] && [ "$TRAVIS_RUST_VERSION" = nightly ]; then
      RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin;
    fi

script:
  - cargo build && cargo test && cargo doc
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cargo build --no-default-features;
    fi

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID;
    fi
